version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "fsd"
      MYSQL_DATABASE: "fsd"
      MYSQL_USER: "fsd"
      MYSQL_PASSWORD: "fsd"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
